### ISSUE TITLE
Flutter Web Audit: tracking issue for bugs

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1421]
We do the majority of our development in the flutter desktop version of DevTools. The Flutter Web version of DevTools needs auditing and polish. This issue should track bugs found while auditing the flutter web app: 
- [x] Splitter click and drag does not work
- [x] Click and drag to scroll in flame chart does not work
- [x] Timeline and memory chart background colors should match the light theme background `Colors.grey[50]`
- [x] Tab bar text color in Inspector details tree should be black
- [x] Tab bar text color in CPU profiler should be black

**Comment by kenzieschmoll** [comment]
All issues are resolved. Closing.
