### ISSUE TITLE
Debugger page rewrite in Flutter

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1648]
# Debugger page Flutter web rewrite

### General
- [x] when initing state, have the script for the rootLib selected
- [x] address some state management issues @kenzieschmoll 
- [x] the debugger should listen for reload events and see if any script source needs to be updated from the VM (`Isolate` / `IsolateReload` kind / `status: "success"`)
- [ ] debounce some of the debugger events (optionally) so things like stepping are smoother (https://github.com/flutter/devtools/issues/1924)

### Call stack 
- [x] implement @kenzieschmoll 

### Variables
- [x] implement @kenzieschmoll 

### breakpoints
- [x] improve display
- [x] update once the source line position has been resolved
- [x] show a count in the area title
- [x] click should jump to the source location
- [x] setting a breakpoint on an unsupported line should set the breakpoint anyway even if it is a noop (ed: we now silently ignore the breakpoint attempt; we could change to provide more feedback to the user)
- [x] have a way to clear all breakpoints
- [ ] persist breakpoints across sessions, per-app (https://github.com/flutter/devtools/issues/1925)

### search in the running app
- [x] improve scripts list display
- [x] move the libraries view to the right side of the screen, have it hidden by default, and have an action button to expand it out in order to search for libraries
- [x] allow searching for classes

### debugger buttons
- [x] Debugging controls for pause, resume, step in, step out, and step over
- [x] improve the appearance so they don't resize on mouse hover
- [x] show a control to configure break on exceptions

### code area
- [x] A view that can show code in Flutter (#1649)
- [x] Line numbering and inline breakpoint markers
- [x] show breakable lines in the gutter
- [x] display the char column of the execution point
- [ ] have forward / back nav. history buttons in the title area (https://github.com/flutter/devtools/issues/1929)
- [ ] show library imports, classes as hyperlinks in the view (based on VM info) (https://github.com/flutter/devtools/issues/1928)
- [ ] syntax highlighting (https://github.com/flutter/devtools/issues/1927)

### console area
- [x] display stdout and stderr text
- [ ] allow for expression evaluation @devoncarew (https://github.com/flutter/devtools/issues/1926)

---

Reference image for the old Flutter plugin view:

![image](https://user-images.githubusercontent.com/14947366/67529782-05788580-f672-11e9-923e-97ca677b8ed2.png)

**Comment by jonahwilliams** [comment]
Drive-by syntax highlighting crazy idea: import the dart parser and use that for tokenization

**Comment by devoncarew** [comment]
For very simple dart syntax highlighting, you could use `package:syntax_highlighter` with `RichText` widgets.

However, we do get a lot of value out of codemirror (your first two bullet points). I think a very feasible option would be to use codemirror as a plugin for the flutter web build of devtools. For non-flutter web builds (like desktop), we could have a less featureful view - that would still support the usecase of using flutter desktop for development.

**Comment by jonahwilliams** [comment]
Looking at the implementation of package:syntax_highlighter, the RegExp based parsing is going to be incredibly slow in desktop AOT builds.

**Comment by devoncarew** [comment]
Yeah, I don't think the lines would be virtualized either. I think it's only an option for trivial cases.

**Comment by DaveShuckerow** [comment]
Some additional thoughts: May be worth holding off on breakpoint visualization; some open-sourced libraries are looking into this as well.

**Comment by jacob314** [comment]
Tagged as M16 for now as this will block making Flutter web the default. This one is definitely at risk of not making M16 so we will need to re-evaluate and move out of the milestone as needed.

**Comment by DaveShuckerow** [comment]
Unassigning myself on account of job change.  Wish you success!

**Comment by kenzieschmoll** [comment]
Closing as we have completed all the blockers - remaining issues are tracked individually.
