### ISSUE TITLE
Making Flutter Web the default version of devtools.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1655]
- [x] Implement debugger page https://github.com/flutter/devtools/issues/1648
- [ ] Fix canvaskit render errors https://github.com/flutter/devtools/issues/1354
- [ ] Polish initial page load for flutter web app https://github.com/flutter/devtools/issues/1468
- [x] delete html app (done in https://github.com/flutter/devtools/pull/1956)

P0 hummingbird bug query:
https://github.com/flutter/devtools/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ahummingbird++label%3AP0+

**Comment by kenzieschmoll** [comment]
0.8.0 is the first release with the Flutter web version as default. Incomplete issues are tracked separately.
