### ISSUE TITLE
app lifecycle improvements

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#1897]
A meta-issue for app lifecycle improvements:
- [x] we should be able to connect to an app, disconnect, and re-connect to a new app in the same devtools session https://github.com/flutter/devtools/issues/1889
- [x] after disconnecting from an app, it would be nice if the data from that session was still available to review; for this, each screen may need to be aware of and handle being in a disconnected state https://github.com/flutter/devtools/issues/1285
- [x] when not connected, it would be nice if some casual information about devtools (the devtools version and where to send feedback) was visible (i.e., make the settings and info buttons active even from the connect screen)
- [ ] diagnose why we see multiple requests to connect to the same connection https://github.com/flutter/devtools/issues/1568
- [x] have a way to disconnect to the existing connection https://github.com/flutter/devtools/issues/1900

**Comment by elliette** [comment]
Closing this out since all tasks have been completed except for the one tracked by https://github.com/flutter/devtools/issues/1568
