### ISSUE TITLE
DevTools Timeline Page: UX Punch List 2020

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#1964]
## Update Overall UX 
- [x] Enlarge Warning Panel:  Current size lends itself to be unengaged
- [x] ~Create Icon for Navigation~
- [ ] Update borders
- [x] ~UX Distinction: Performance Overlay, Track Widget Builds, Network~
- [x] Scrolling Tabs: use a consistent scroll physics for the TabViewBar widget

- [x] **Update/Add unified color themes**
- - [x] ~Multiple issues with light mode.~
- -  [x] Update page's default font color to default Light mode font color. 
- - [x] Rows need alternate colors: color serves as distinction between threads. (Currently: Light Blue = UI, Dark Blue = Raster)
- - -[x] UI Blues: `#88b1de`
- - -[x] Raster Blues: `#2c5daa`
- -  [x] Jank: `#c3595a`.  `#f5846b`

- - [x] Update selected color from gray to its original color. 
- - [x]  Bracket color and select indicator:`#36c6f4`

## Timeline and Flame Chart
- [x] Add sticky legend
- [ ] Add Mini Map (tracked separately here: https://github.com/flutter/devtools/issues/2094)
- [x] Use DevTools standard table
- [x] ~Make Overflow Menu enabled by default~

#### Current ( DevTools 0.2.5 Timeline Page)

![image](https://user-images.githubusercontent.com/8105802/81957819-f92e2880-95c1-11ea-8313-8fd5432c0c42.png)
![image](https://user-images.githubusercontent.com/8105802/81957936-1c58d800-95c2-11ea-9155-0156b6a03062.png)
![image](https://user-images.githubusercontent.com/8105802/81957979-2bd82100-95c2-11ea-9b79-c19d003ae2e6.png)

:sparkles:
####  UX Punch List Updates:

**Comment by kenzieschmoll** [comment]
Note: some of these issues look like they belong to the Network page instead of the timeline page

**Comment by raison00** [comment]
I've removed a few network items.  thanks for the catch!

**Comment by kenzieschmoll** [comment]
what do you mean by "Create Icon for Navigation"?

**Comment by raison00** [comment]
@kenzieschmoll  I will create some designs to express the navigation and post them here.  I have gone through my notes a few times today to see why this was added to the punch list. It's not really a line item anymore, so I will remove it - but the concept for navigation clarity remains the core of the issue and is based on the UX Distinction: Performance Overlay, Track Widget Builds, Network 
![profile-granulary](https://user-images.githubusercontent.com/8105802/83822871-27fe6280-a687-11ea-9ba3-3e3e2c49a0ba.png)
The "Create Icon for Navigation" stems from the double Network options needing clarity and distinction:
![image](https://user-images.githubusercontent.com/8105802/83822911-4a907b80-a687-11ea-8b69-5f5a723955b3.png)
 I will additional designs here later tonight to help visualize the distinction.

**Comment by kenzieschmoll** [comment]
The network logging option is no longer a button at the top of the timeline. It was moved into the new overflow menu that contains recording stream options
<img width="805" alt="Screen Shot 2020-06-05 at 8 12 51 AM" src="https://user-images.githubusercontent.com/43759233/83893152-730a8b00-a704-11ea-9cc8-b301466b719f.png">
<img width="752" alt="Screen Shot 2020-06-05 at 8 12 57 AM" src="https://user-images.githubusercontent.com/43759233/83893162-756ce500-a704-11ea-945a-a7cbde1b1bd8.png">

**Comment by raison00** [comment]
![timeline-flow-arrow-final](https://user-images.githubusercontent.com/8105802/84061529-e9acc000-a972-11ea-9b71-a0a63934359f.png)

**Comment by raison00** [comment]
## Timeline bar colors:
- [ ] Selected: `#4e4f4f`
- [ ] UI Blues: `#88b1de`
- [ ] Raster Blues: `#2c5daa`
-  [ ] Jank: `#c3595a`.  `#f5846b`
-  [ ] Jank:  `#f5846b`
## Flow Chart
- [ ] Selected: `#4e4f4f`
-  [ ] Blue arrow + flow info with a 4pt stroke:  `#36c6f4`.

**UI Flow Colors:**
- [ ] `#88b1de`
-  [ ] `#6793cd`

**Raster Flow Colors:**
-  [ ] `#386eb6`
-  [ ] `#2c5daa`

**Comment by raison00** [comment]
Here's a mock of the light version with minor changes from the dark version:
- [ ] Selected color: `#dbdddd`
- [ ] Font color change to black

![timeline-light-flow-arrow-v3](https://user-images.githubusercontent.com/8105802/84076562-d7d71700-a98a-11ea-9a5b-fd5c02dff162.png)

**Comment by kenzieschmoll** [comment]
@raison00 do you have a suggestion for the selected event color? This is what we use currently.
![Screen Shot 2020-06-09 at 4 06 24 PM](https://user-images.githubusercontent.com/43759233/84209675-94a0a500-aa6b-11ea-9a54-39a4c05862a8.png)
![Screen Shot 2020-06-09 at 4 09 32 PM](https://user-images.githubusercontent.com/43759233/84209696-a08c6700-aa6b-11ea-927a-2ce324edcf13.png)

**Comment by kenzieschmoll** [comment]
> Should we turn on recording traffic as soon as the user gets on this page, or in the background?
> Listen to Timeline events from service instead of polling? Or increase the rate at which we poll?
> Fix Timestamp: remove year

These all seem like they belong to the network page UX punch list issue

**Comment by raison00** [comment]
![Selected-color-FlameChart](https://user-images.githubusercontent.com/8105802/84326700-6df97180-ab32-11ea-881b-0757b88ea623.jpg)

![select-flamechart](https://user-images.githubusercontent.com/8105802/84326611-31c61100-ab32-11ea-9aa8-4817445d2199.jpg)

**Comment by kenzieschmoll** [comment]
What does "Make Overflow Menu enabled by default" mean?

**Comment by kenzieschmoll** [comment]
Could also use an explanation on "Multiple issues with light mode." - thanks

**Comment by raison00** [comment]
I believe most issues with light mode have been resolved as updates have been made.  When this list was first created, white text on a white background was an issue and other necessary updates that are now resolved.

**Comment by kenzieschmoll** [comment]
All issues are either resolved or being tracked in other issues 🎉
