### ISSUE TITLE
Post-html-delete cleanup [meta tracking issue]

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1965]
- [ ] Audit app startup from server
- [ ] Audit service manager code and convert stream patterns to ValueListenable patterns
- [ ] Audit controllers and delete dead code, convert streams patterns to ValueListenable patterns where possible
  - [ ] Inspector @jacob314 
  - [ ] Timeline @kenzieschmoll 
  - [ ] Memory @terrylucas 
  - [ ] Performance @kenzieschmoll 
  - [ ] Debugger
  - [ ] Network
  - [ ] Logging
  - [ ] Info
- [ ] Hook up analytics to flutter app if anything was broken during html delete @terrylucas

**Comment by kenzieschmoll** [comment]
@DanTup do you have time to take a look at the integration tests and fixing the build from server? You probably have the most knowledge of this code.

**Comment by DanTup** [comment]
> @DanTup do you have time to take a look at the integration tests and fixing the build from server? You probably have the most knowledge of this code.

I'm a little less familiar with the non-server tests, but my understanding from the comments at https://github.com/flutter/devtools/pull/1902#issuecomment-623570632 is that these tests won't be ported over (they're tightly-coupled to the HTML app - or at least - the testing interface that was part of it) and instead replaced with Flutter widget/driver tests.

It may be worth extracting a list of the tests into an issue before removing the old ones that can be worked through.

**Comment by DanTup** [comment]
> and fixing the build from server?

Missed this - but not sure exactly what this refers to?

**Comment by kenzieschmoll** [comment]
> > and fixing the build from server?
> 
> Missed this - but not sure exactly what this refers to?

If you try launch the app via `serveDevToolsWithArgs` from the server, it fails. I usually do this by running the publish script, and then running `dart devtools/bin/devtools.dart`.

**Comment by DanTup** [comment]
@kenzieschmoll is the problem that it launches with to a white empty page? If so, that will be fixed by https://github.com/flutter/devtools/pull/1975 - the script was still building both versions and putting the Flutter version at `/flutter.html`.
