### ISSUE TITLE
DevTools Memory Page: UX Punch List 2020

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#1974]
##
## Update Overall UX 
 - [ ] Update Time Range Slider for optimized layout
 - [x] Add legend to right side of Dart Memory Heap graph
 - [x] Add legend to right side of Android Memory graph
- [ ] Show Android data by default when connected to an Android app
 - [ ] Remove Android Memory CTA if not connected to an Android app
 - [ ] Move Android Memory CTA: visible on conditional: if available, display button to top of page
- [ ] Make Export Memory button consistent with other export buttons (ie: match the Timeline page)
- [ ] Update the processing spinner on the Snapshot table, it should be centered vertically. 
- [x] Make tab for Heat Map instead of toggle/slider: convert to tab view with two tabs (one for Heat Map  and one for Snapshot table)
- [ ] Make Search bar consistent from Heat Map & Snapshot
- [x] Consider switching from Heat Map to Tree Map 
**Note:** [UX UI Color Updates for Tree Map](https://github.com/flutter/devtools/issues/2139)
- [ ] Make a small thumbnail of the Heat Map/Tree Map in the right of the timeline to give quick visual context 
- [ ] Gain better insight into the non-Dart Heap Memory
- - [ ] Visualize size and ability to surface non-Dart Heap Objects
- - [ ] Add visualization and raise awareness of where memory resources are allotted

##
- [ ] Unify Search & Filter Expectations 
- - [ ] Keep Search bar in Snapshot table view
- - [ ] Update bottom bar filter based on search/hide 
- - [ ] When search / filter is applied, show message same as logging page (IE: “showing 300 of 400”)
- - [ ] Specify Filter and visualize it (split screen: snapshot table on left, tree map on right) with capabilities to drill into each instance (with pagination) and maintain the visualization tree mapping context
-  - [ ] Can we combine search & filter? 
- - [ ] How does search work with - filters?
- - [ ] Advanced Search / Filter? UXR Testing to determine best practices to adopt

##
-  [ ] **Match global UX of DevTools pages**

- - [ ] Add orders as consistent with DevTools pages
- - [ ] Update Charts on page to align with DevTools (theme changes aren't always respected on current page)
- - [ ] Consider options for visualization and Snapshot information at the same time
- - [ ] Update spacing, padding of data entries
- - [ ] Add Header to bottom area to define section
- - [x] Use DevTools standard table
- - [x] Clean-up the design, less _busy_
- - [ ]  Update UX Patterns for consistent modification of granularity
- - [ ] Make Chart size consistent across DevTools (ie: match the Timeline page)
##
- [ ] **Update Default font color, font weight to align with DevTools global styles**
 - - [ ] Ensure icon colors render correctly and consistently 
- - [ ] Dropdowns currently rendering red text: update to colors outlined below
- - [ ] Should we revisit banner colors?
- - [ ] Update all colors to resolve visibility issues created by some defaults(colors below)
- - [x] Update Chart themes to ensure the correct user experience. Hot Reload will resolve style issues of dark/light mode 

##
- [ ] **Update/Add unified color themes**
##
 - [ ] **Dark Mode:** Update Text color to `#3477db` and Text Weight to _500_ for the _External_ label in the Legend
 - [ ] **Dark Mode:** `.btn-primary`: Update Resume Button color to `#28a745` for the _Play / Resume Button_  
 - [ ] **Dark Mode:** `.btn-primary`: Update _Active_ Resume Button color to `#08751f` for the _Active Play / Resume Button_  

##
 - [ ] **Light Mode:** Update Text color to `#504e4e` and Text Weight to _500_ of the _Drop Down Title_ for visibility, readability, accessibility 

 - [ ] **Light Mode:** `.btn-primary`: Update Resume Button color to `#28a745` for the _Play / Resume Button_  
- [ ] **Light Mode:** `.btn-primary`: Update _Active_ Resume Button color to `#08751f` for the _Active Play / Resume Button_
##

#### Current ( DevTools 0.2.5 Memory Page)
![image](https://user-images.githubusercontent.com/8105802/82098308-928c3600-96b9-11ea-810a-043cf98bb792.png)

![image](https://user-images.githubusercontent.com/8105802/82098537-fc0c4480-96b9-11ea-8a6e-b2582f9c7083.png)

![image](https://user-images.githubusercontent.com/8105802/82098581-134b3200-96ba-11ea-9749-5f7a35254c8c.png)

![image](https://user-images.githubusercontent.com/8105802/82098677-44c3fd80-96ba-11ea-8f05-60ce6efb14fc.png)
![image](https://user-images.githubusercontent.com/8105802/82098700-53121980-96ba-11ea-8bb6-a9be11493a4b.png)
![image](https://user-images.githubusercontent.com/8105802/82099039-227eaf80-96bb-11ea-858c-033b020bf8a5.png)
![image](https://user-images.githubusercontent.com/8105802/82101878-9bcdd080-96c2-11ea-94ed-9215e7a2a2b1.png)

![image](https://user-images.githubusercontent.com/8105802/82101861-8f497800-96c2-11ea-89c1-c84114cff6f0.png)

:sparkles:
####  UX Punch List Updates:
![image](https://user-images.githubusercontent.com/8105802/82101632-daaf5680-96c1-11ea-83a4-23715b3ba281.png)
![image](https://user-images.githubusercontent.com/8105802/82101648-e733af00-96c1-11ea-8abd-c1a058d02283.png)
![image](https://user-images.githubusercontent.com/8105802/82101721-22ce7900-96c2-11ea-89ac-30852bd861eb.png)

**Comment by cobblest** [comment]
Additional items from [memory debugging CUJ study](https://docs.google.com/presentation/d/1I3FoY2bGiR8I0GRSmld4DrBMMciyIOZHudAwa3W7Glc/edit#slide=id.g89bb417694_0_24) 

- Make the table view as default view when taking snapshots 
- Remove Setting if there is no options
- Make the format in Shallow and Retained consistent 
- Show stack trace on allocation of the critical objects (e.g. image, graphics, animations)

**Comment by raison00** [comment]
@cobblest @terrylucas I've updated the Punch List to include discussion points and study results.  I will continue to update/refine it as I unify the DevTools pages in the coming days.

**Comment by jacob314** [comment]
Is there anything on this punch list that is still relevant or should this be closed? Found this as there were some accessibility comments.

**Comment by kenzieschmoll** [comment]
Closing as obsolete with the memory page rewrite
