### ISSUE TITLE
DevTools Inspector Page: Layout Explorer UX Updates

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#2101]
**Update/Add unified color themes**

- [x] Main Axis: `#1375bc`
 - [x] Row: `#2c5daa`
- [x] Cross Axis: `#8ac652`
 - [x] Column: `#77974d`
 - [x] Selected Widget: `#36c6f4`
- [x] Unselected: `#88b1de`
- [x] Emphasized Text, Arrows: `#009aca`
 - [x] Text, Arrows:  `#55767f`
- [x] Unconstrained: `#f5846b`
- [x] De-emphasized Unconstrained: `#dea089`

##
 **Empty Space, aka Negative Space**
 - [x] Negative Space:  `#51bade` at 30% opacity
 - [x] Negative Space:  `#386c7d` at 30% opacity
 - [x] Background Color Dark:  `#303030`
 - [x] Background Color Light:  `#ffffff`

##
 **Tiled Swatches for Negative Space:**
 **Dark Mode Specific Update: Tiled Swatch for Negative Space: 20% opacity to recede into background**
![image](https://user-images.githubusercontent.com/8105802/85625747-c3e51380-b620-11ea-90c6-7866f38d05e2.png) | ![swatch1-light-mode](https://user-images.githubusercontent.com/8105802/85625585-8bddd080-b620-11ea-94ee-d20b320ccc45.png)
 **Light Mode Specific Update: Tiled Swatch for Negative Space: 30% opacity to recede into background**
##
 **Dark Mode Specific Updates**
- [x] Selected Background Area: `#edeeef` at 30% opacity
- [x] Default Font Color: `#ffffff`

##
 **Light Mode Specific Updates**
- [x] Selected Background Area: `#edeeef`
- [x] Default Font Color: `#000000`
- [x] De-emphasized Font Color: `#505050` (if needed)

Dark Mode Updates:
![layout-explorer-dark](https://user-images.githubusercontent.com/8105802/85072259-a0781f80-b16d-11ea-961c-f3ce36883be2.png)

Light Mode Updates:

![layout-explorer-light](https://user-images.githubusercontent.com/8105802/85072283-b259c280-b16d-11ea-883e-ee2426c780ad.png)
