### ISSUE TITLE
Burndown list to enable the provider page by default

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#2972]
- [x] Eliminate hangs opening providers https://github.com/flutter/devtools/issues/2971
- [x] Normalize colors and style with debugger object view. For the most part the provider UX is superior. However displying the number of elements (fields) for objects seems questionable. https://github.com/flutter/devtools/issues/2987
- [x] Fix value editing UI which doesn't have enough whitespace. (only repros on web)
- [x] Provider screen shows spinning icon for some apps that never goes away https://github.com/flutter/devtools/issues/2980
- [x] Provider screen fails to update after a hot restart. https://github.com/flutter/devtools/issues/2977

**Comment by jacob314** [comment]
Fyi @rrousselGit

**Comment by rrousselGit** [comment]
> Evaluate whether a refresh button is needed or the expected behavior is that providers will be displayed when available.

The current behavior is, if there is no selected provider but there is one provider in the list, the provider is selected. 

I handled all scenarios where this could happen. Such as when the selected provider is unmounted in the inspected ap


So unless there are no providers in the application, one provider will be selected.

**Comment by jacob314** [comment]
> > Evaluate whether a refresh button is needed or the expected behavior is that providers will be displayed when available.
> 
> The current behavior is, if there is no selected provider but there is one provider in the list, the provider is selected.
> 
> I handled all scenarios where this could happen. Such as when the selected provider is unmounted in the inspected ap
> 
> So unless there are no providers in the application, one provider will be selected.

I played around and in general updating the providers works beautifully. It appears there is a race condition the first time the provider screen is opened for an app. Added a bug with details on how to repro. Seems very reliable on the simple provider sample apps.

**Comment by rrousselGit** [comment]
Could you expand on what the following is about?

> Normalize colors and style with debugger object view. For the most part the provider UX is superior. However displying the number of elements (fields) for objects seems questionable.

**Comment by jacob314** [comment]
> Could you expand on what the following is about?
> 
> > Normalize colors and style with debugger object view. For the most part the provider UX is superior. However displying the number of elements (fields) for objects seems questionable.
Broke this out into a bug.
https://github.com/flutter/devtools/issues/2987

**Comment by kenzieschmoll** [comment]
AFAICT, all these issues have been resolved. Please reopen if that is incorrect.
