### ISSUE TITLE
[ Tracking Issue ] Observatory -> DevTools Migration

### ISSUE THREAD

**Issue by bkonyi** [flutter/devtools#3858]
Tracking issue for the Observatory migration effort.

**Performance + Size Issues (P1)**
- [ ] https://github.com/flutter/devtools/issues/4791 (p5)
- [x] https://github.com/flutter/devtools/issues/5091 (p4)

**Core Functionality**
- [x] https://github.com/flutter/devtools/issues/4207
- [x] https://github.com/flutter/devtools/issues/3859
- [x] https://github.com/flutter/devtools/issues/3862
- [ ] https://github.com/flutter/devtools/issues/3867 (p5)
- [x] https://github.com/flutter/devtools/issues/3869
- [x] https://github.com/flutter/devtools/issues/3874
- [x] https://github.com/flutter/devtools/issues/3861 (p2)

**Advanced Functionality**
- [x] https://github.com/flutter/devtools/issues/3860
- [x] https://github.com/flutter/devtools/issues/2210
- [x] https://github.com/flutter/devtools/issues/3878
- [x] https://github.com/flutter/devtools/issues/3910

**Comment by kenzieschmoll** [comment]
Do we have usage metrics from Observatory on any of the missing features so that we can prioritize which ones we work on first? Or decide if any tools should be left out completely if users hardly use them?

**Comment by bkonyi** [comment]
> Do we have usage metrics from Observatory on any of the missing features so that we can prioritize which ones we work on first? Or decide if any tools should be left out completely if users hardly use them?

Unfortunately not. I'm going to go through advanced features with the VM team (maybe some engine folks) to see what they use and would want migrated. There's already some features (e.g., Observatory's heap map) that we won't bother migrating.

So far I've only created issues for features that are actually useful or extend existing functionality (I'm sure I'll have more filed tomorrow).

**Comment by a-siva** [comment]
In the list of core/advanced functionality being tracked I do not see the issue of general devtools snappiness, do we have an issue tracking that ?

**Comment by elliette** [comment]
Closing this tracking issue since the migration has been completed.
