### ISSUE TITLE
P2: Dark theme tweaks/polish

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#418]
- [x] Consider changing blue headings on Debugger panes #419
- [x] Pause button has a black icon but others are white #423
- [x] Background may be too dark
- [x] the chartly charts don't match the dark theme
- [x] the help link in the button right has a black icon but others are white #431
- [x] we should choose a different accent color for the dark theme (currently we're using the light theme's green color - see the 'primary' buttons in each page)
- [ ] the buttons don't have gradients
- [x] the warning dialog color (see the inspector page when a app is run from the cli) doesn't work well in the dark theme #431
- [x] debugger breakpoints are too faint in the dark theme, and have turned blue in the light theme  #419
- [x] ~it's difficult to distinguish between enabled/disabled/selected button states https://github.com/flutter/devtools/issues/576~
- [x] the debugger execution point is hard to see #419
- [x] mouse over of hyperlinks uses a blue color; perhaps we should use 'wheat'? #431
