### ISSUE TITLE
Prepare Release Notes for 2.21.0 release

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#4982]
# Description
Modifying the release notes will now be enforced by our GH workflow. Added here: https://github.com/flutter/devtools/commit/f6003ac57a32653e15afbe7648b5453b2296cc93

We still need to ensure that the previous changes for the release are added to the readme file though.
The Next section will be used to tag and notify any contributors that need to modify the README.

# Contributions that need to be accounted for
> **Checked off items are already handled** 

- [x] Fix regex for release notes  process so it doesn't catch template [#4980](https://github.com/flutter/devtools/pull/4980)
- [x] Fix a number more issues by enabling Dart code metrics [#4931](https://github.com/flutter/devtools/pull/4931)
- [x] Github Workflow Changes for Release Note Process [#4961](https://github.com/flutter/devtools/pull/4961)
- [x] Bump actions/checkout from 3.1.0 to 3.2.0 [#4937](https://github.com/flutter/devtools/pull/4937)
- [x] Bump github/codeql-action from 2.1.36 to 2.1.37 [#4951](https://github.com/flutter/devtools/pull/4951)
- [x] - [#4977](https://github.com/flutter/devtools/pull/4977)
- [x] Add Safari fix + grammar update to release notes [#4966](https://github.com/flutter/devtools/pull/4966)
    - [ ] https://github.com/flutter/devtools/pull/4983 
- [x] Integration test 2 [#4969](https://github.com/flutter/devtools/pull/4969)
- [x] Bump ossf/scorecard-action from 2.1.0 to 2.1.1 [#4971](https://github.com/flutter/devtools/pull/4971)
- [x] Add initial framework for integration testing [#4960](https://github.com/flutter/devtools/pull/4960)
- [x] Update allocation_profile_table_view_controller.dart [#4968](https://github.com/flutter/devtools/pull/4968)
    - @polina-c this may need a Release note Entry 
- [x] - [#4965](https://github.com/flutter/devtools/pull/4965)
- [x] UX improvements for diff [#4958](https://github.com/flutter/devtools/pull/4958)
    - @polina-c this may need a Release note Entry 
- [x] Rename old integration_test folder to legacy_integration_tests [#4959](https://github.com/flutter/devtools/pull/4959)
- [x] Rename some variables [#4956](https://github.com/flutter/devtools/pull/4956)
- [x] Stop double counting self-referenced classes [#4955](https://github.com/flutter/devtools/pull/4955)
    - @polina-c this may need a Release note Entry 
- [x] Rename no-package-libraries to dart-internal-objects [#4954](https://github.com/flutter/devtools/pull/4954)
- [x] Customizing our Pull Request Template [#4762](https://github.com/flutter/devtools/pull/4762)
- [x] Revert accidental removal [#4953](https://github.com/flutter/devtools/pull/4953)
- [x] Bump ossf/scorecard-action from 2.0.4 to 2.1.0 [#4952](https://github.com/flutter/devtools/pull/4952)
- [x] Patch and Dev Bump to start our new release version process [#4950](https://github.com/flutter/devtools/pull/4950)
- [x] Daily Dev Bumps [#4908](https://github.com/flutter/devtools/pull/4908)
- [x] Update case study on memory leaks [#4942](https://github.com/flutter/devtools/pull/4942)
- [x] Update syntax highlighting grammar [#4948](https://github.com/flutter/devtools/pull/4948)
- [x] Don't fail at startup if textmate grammar can't be parsed by browser [#4938](https://github.com/flutter/devtools/pull/4938)
- [x] Fixes from code metrics lints [#4890](https://github.com/flutter/devtools/pull/4890)
- [x] Use enhanced enum for screen ids and titles [#4940](https://github.com/flutter/devtools/pull/4940)
- [x] Pin bots to a version of Flutter before Dart 3 [#4944](https://github.com/flutter/devtools/pull/4944)
- [x] Update main.dart [#4932](https://github.com/flutter/devtools/pull/4932)
- [x] Update-version script changes [#4910](https://github.com/flutter/devtools/pull/4910)
- [x] Bump github/codeql-action from 2.1.35 to 2.1.36 [#4933](https://github.com/flutter/devtools/pull/4933)
- [ ] Stop changing tooltip on state change [#4928](https://github.com/flutter/devtools/pull/4928)
    - @polina-c this may need a Release note Entry 
- [x] Add support for specifying initial tab selection on AnalyticsTabbedView [#4927](https://github.com/flutter/devtools/pull/4927)
    - @kenzieschmoll this may need a Release note Entry
- [x] Scroll flutter frames chart to selected frame on first load [#4930](https://github.com/flutter/devtools/pull/4930)
- [x] Fix offline mode bug in the legacy timeline events viewer [#4929](https://github.com/flutter/devtools/pull/4929)
    - @kenzieschmoll this may need a Release note Entry
- [x] Clean up About dialog [#4926](https://github.com/flutter/devtools/pull/4926)
    - @kenzieschmoll this may need a Release note Entry 
- [x] Remove outline from Provider settings button [#4925](https://github.com/flutter/devtools/pull/4925)
    - @kenzieschmoll this may need a Release note Entry 
- [x] Reorganize memory screen code [#4911](https://github.com/flutter/devtools/pull/4911)
- [x] Reorganize code - 2 [#4909](https://github.com/flutter/devtools/pull/4909)
- [x] Reorganize code [#4907](https://github.com/flutter/devtools/pull/4907)
- [x] Add support for displaying profiler hits for a script in `CodeView` [#4831](https://github.com/flutter/devtools/pull/4831)
    - @bkonyi  this may need a Release note Entry 
- [x] Update latest flutter candidate script to use simpler commands [#4849](https://github.com/flutter/devtools/pull/4849)
- [x] Integrate leak_tracker [#4891](https://github.com/flutter/devtools/pull/4891)
    - @polina-c this may need a Release note Entry 
- [x] Fix routing test [#4903](https://github.com/flutter/devtools/pull/4903)
- [x] Add initial support for non-query param navigation state [#4837](https://github.com/flutter/devtools/pull/4837)
    - @bkonyi  this may need a Release note Entry 
- [x] Delete perfetto files related to legacy catapult trace viewer [#4899](https://github.com/flutter/devtools/pull/4899)
- [x] Set documentation links on memory page [#4896](https://github.com/flutter/devtools/pull/4896)
    - @polina-c this may need a Release note Entry 
- [x] Update the Perfetto assets and remove js sourcemaps [#4897](https://github.com/flutter/devtools/pull/4897)
- [x] Reorganize constants to be closer to place where they are used [#4895](https://github.com/flutter/devtools/pull/4895)
- [x] Fix legend to show dash line [#4892](https://github.com/flutter/devtools/pull/4892)
    - @polina-c this may need a Release note Entry 
- [x] Move Performance feature controls into tab view [#4889](https://github.com/flutter/devtools/pull/4889)
    - @kenzieschmoll this may need a Release note Entry 
- [x] Rename rebuild_stats files [#4888](https://github.com/flutter/devtools/pull/4888)
- [x] Remove unnecessary Future types in Perfetto code [#4864](https://github.com/flutter/devtools/pull/4864)
- [x] Fix type error in Perfetto code [#4863](https://github.com/flutter/devtools/pull/4863)
- [x] Add launch configuration to enable experiments [#4862](https://github.com/flutter/devtools/pull/4862)
- [x] Disable experiments for debug and profile mode [#4861](https://github.com/flutter/devtools/pull/4861)
- [x] Bump github/codeql-action from 2.1.32 to 2.1.35 [#4858](https://github.com/flutter/devtools/pull/4858)
- [x] Clean up memory page UI and DevTools paddings [#4855](https://github.com/flutter/devtools/pull/4855)
    - @kenzieschmoll this may need a Release note Entry 
- [x] Fix typos in codebase [#4850](https://github.com/flutter/devtools/pull/4850)
- [x] Add link to view release notes from About dialog [#4848](https://github.com/flutter/devtools/pull/4848)
- [x] Update release instructions [#4844](https://github.com/flutter/devtools/pull/4844)
- [x] Update BETA_TESTING.md [#4830](https://github.com/flutter/devtools/pull/4830)
- [x] Reorganize leak tracking code [#4832](https://github.com/flutter/devtools/pull/4832)

**Comment by CoderDake** [comment]
All issues have been accounted for. NEXT_RELEASE_NOTES.md should now always be up to date with release notes!
