### ISSUE TITLE
Tracking issue for DevTools related Perfetto requests / bugs

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#5245]
bug hotlist: 4148010
- [ ] support a dark theme: b/246338404
- [ ] Configurable track order from post message API: b/259303986
- [ ] register a notifyOnSelected handler in the postMessage api: b/249828626
- [ ] overall UI density: added a comment to existing issue https://github.com/google/perfetto/issues/429

Early feedback from Dart / Flutter team members:
- [ ] timeline start and end time: https://github.com/google/perfetto/issues/446
- [ ] track overflow issues: https://github.com/google/perfetto/issues/447
- [ ] accessibility: https://github.com/google/perfetto/issues/448

Labeling as blocked since the fixes will need to happen in perfetto and not devtools.
