### ISSUE TITLE
[CPU Profiler] Meta tracking issue for initial feedback

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#631]
- [x] Add duration stack frame description - https://github.com/flutter/devtools/pull/630

- [x] Account for all leaf nodes in our UI. We are currently dropping samples where a leaf node has children in other samples.

- [ ] Investigate sample rate not matching results. Experiment with increasing rate - Sample rate can now be specified by a profile granularity selector. Tracking issue for investigating sample count here: https://github.com/flutter/devtools/issues/937

- [x] Improve truncation problem. Stitch truncated samples into profile or increase stack depth - we can increase the stack depth by running the app with `--dart-flags=--max_profile_depth=256`

- [ ] Color stack frames based on their category (dart, rendering, paint, etc) - this is blocked by https://github.com/dart-lang/sdk/issues/37553. If we do not have the resolved urls in profile mode, we can't be certain on which packages stack frames are from.  Tracking issue for this is https://github.com/flutter/devtools/issues/578

**Comment by kenzieschmoll** [comment]
Closing this issue as the unresolved issues have their own tracking issues.
