### ISSUE TITLE
Research options for disposable and leak tracker MVP

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#6555]
- [ ] Experiment with kernel transformations
- [ ] Prototype library level flag
- [x] Get data from G3 about ChangeNotifier usage
- [ ] Update [disposable](http://flutter.dev/go/introduce-disposable)
- [ ] Update [leak_tracker MVP](https://docs.google.com/document/d/1hlGY6HnsH5EJhpQDFm-_e-Sr9euQf6jE74TxkqDxhGY/edit?resourcekey=0--7J08lEADd6HpaTGC1B-Pw)
- [ ] Schedule [meeting with language team](https://docs.google.com/document/d/1cCWECTj4hC-FQbkwiwBa7hRPYhk58Y1J_UAamD0I6VA/edit?resourcekey=0-s42S5aAjWFI1FLkiu9WWEA)

**Comment by polina-c** [comment]
Options for compile time flag: condition for dispatchCreation, flag in pubspec.yaml.

**Comment by polina-c** [comment]
Closed as duplicate with https://github.com/flutter/devtools/issues/6909
