### ISSUE TITLE
Meta tracking issue for showing more inspector trees

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6614]
- [ ] Render tree - https://github.com/flutter/devtools/issues/6603
- [ ] Semantics tree - https://github.com/flutter/devtools/issues/1397
- [ ] Focus tree - https://github.com/flutter/devtools/issues/5326
- [ ] Layer tree - https://github.com/flutter/devtools/issues/481
